// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mojoroutes/routes.proto

package mojomusic

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PlayRequest struct {
	Greeting             string   `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayRequest) Reset()         { *m = PlayRequest{} }
func (m *PlayRequest) String() string { return proto.CompactTextString(m) }
func (*PlayRequest) ProtoMessage()    {}
func (*PlayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab0a5b77bdd242d, []int{0}
}

func (m *PlayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayRequest.Unmarshal(m, b)
}
func (m *PlayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayRequest.Marshal(b, m, deterministic)
}
func (m *PlayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayRequest.Merge(m, src)
}
func (m *PlayRequest) XXX_Size() int {
	return xxx_messageInfo_PlayRequest.Size(m)
}
func (m *PlayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlayRequest proto.InternalMessageInfo

func (m *PlayRequest) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

type PlayResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayResponse) Reset()         { *m = PlayResponse{} }
func (m *PlayResponse) String() string { return proto.CompactTextString(m) }
func (*PlayResponse) ProtoMessage()    {}
func (*PlayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab0a5b77bdd242d, []int{1}
}

func (m *PlayResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayResponse.Unmarshal(m, b)
}
func (m *PlayResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayResponse.Marshal(b, m, deterministic)
}
func (m *PlayResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayResponse.Merge(m, src)
}
func (m *PlayResponse) XXX_Size() int {
	return xxx_messageInfo_PlayResponse.Size(m)
}
func (m *PlayResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlayResponse proto.InternalMessageInfo

func (m *PlayResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type SkipRequest struct {
	Greeting             string   `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SkipRequest) Reset()         { *m = SkipRequest{} }
func (m *SkipRequest) String() string { return proto.CompactTextString(m) }
func (*SkipRequest) ProtoMessage()    {}
func (*SkipRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab0a5b77bdd242d, []int{2}
}

func (m *SkipRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SkipRequest.Unmarshal(m, b)
}
func (m *SkipRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SkipRequest.Marshal(b, m, deterministic)
}
func (m *SkipRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SkipRequest.Merge(m, src)
}
func (m *SkipRequest) XXX_Size() int {
	return xxx_messageInfo_SkipRequest.Size(m)
}
func (m *SkipRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SkipRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SkipRequest proto.InternalMessageInfo

func (m *SkipRequest) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

type SkipResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SkipResponse) Reset()         { *m = SkipResponse{} }
func (m *SkipResponse) String() string { return proto.CompactTextString(m) }
func (*SkipResponse) ProtoMessage()    {}
func (*SkipResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab0a5b77bdd242d, []int{3}
}

func (m *SkipResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SkipResponse.Unmarshal(m, b)
}
func (m *SkipResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SkipResponse.Marshal(b, m, deterministic)
}
func (m *SkipResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SkipResponse.Merge(m, src)
}
func (m *SkipResponse) XXX_Size() int {
	return xxx_messageInfo_SkipResponse.Size(m)
}
func (m *SkipResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SkipResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SkipResponse proto.InternalMessageInfo

func (m *SkipResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type StopRequest struct {
	Greeting             string   `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopRequest) Reset()         { *m = StopRequest{} }
func (m *StopRequest) String() string { return proto.CompactTextString(m) }
func (*StopRequest) ProtoMessage()    {}
func (*StopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab0a5b77bdd242d, []int{4}
}

func (m *StopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopRequest.Unmarshal(m, b)
}
func (m *StopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopRequest.Marshal(b, m, deterministic)
}
func (m *StopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopRequest.Merge(m, src)
}
func (m *StopRequest) XXX_Size() int {
	return xxx_messageInfo_StopRequest.Size(m)
}
func (m *StopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopRequest proto.InternalMessageInfo

func (m *StopRequest) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

type StopResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopResponse) Reset()         { *m = StopResponse{} }
func (m *StopResponse) String() string { return proto.CompactTextString(m) }
func (*StopResponse) ProtoMessage()    {}
func (*StopResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab0a5b77bdd242d, []int{5}
}

func (m *StopResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopResponse.Unmarshal(m, b)
}
func (m *StopResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopResponse.Marshal(b, m, deterministic)
}
func (m *StopResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopResponse.Merge(m, src)
}
func (m *StopResponse) XXX_Size() int {
	return xxx_messageInfo_StopResponse.Size(m)
}
func (m *StopResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopResponse proto.InternalMessageInfo

func (m *StopResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*PlayRequest)(nil), "mojomusic.PlayRequest")
	proto.RegisterType((*PlayResponse)(nil), "mojomusic.PlayResponse")
	proto.RegisterType((*SkipRequest)(nil), "mojomusic.SkipRequest")
	proto.RegisterType((*SkipResponse)(nil), "mojomusic.SkipResponse")
	proto.RegisterType((*StopRequest)(nil), "mojomusic.StopRequest")
	proto.RegisterType((*StopResponse)(nil), "mojomusic.StopResponse")
}

func init() { proto.RegisterFile("mojoroutes/routes.proto", fileDescriptor_5ab0a5b77bdd242d) }

var fileDescriptor_5ab0a5b77bdd242d = []byte{
	// 208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcf, 0xcd, 0xcf, 0xca,
	0x2f, 0xca, 0x2f, 0x2d, 0x49, 0x2d, 0xd6, 0x87, 0x50, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42,
	0x9c, 0x20, 0x89, 0xdc, 0xd2, 0xe2, 0xcc, 0x64, 0x25, 0x4d, 0x2e, 0xee, 0x80, 0x9c, 0xc4, 0xca,
	0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x29, 0x2e, 0x8e, 0xf4, 0xa2, 0xd4, 0xd4, 0x92,
	0xcc, 0xbc, 0x74, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x38, 0x5f, 0x49, 0x8d, 0x8b, 0x07,
	0xa2, 0xb4, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48, 0x8c, 0x8b, 0xad, 0x28, 0xb5, 0xb8, 0x34,
	0xa7, 0x04, 0xaa, 0x12, 0xca, 0x03, 0x19, 0x19, 0x9c, 0x9d, 0x59, 0x40, 0xa4, 0x91, 0x10, 0xa5,
	0x44, 0x18, 0x59, 0x92, 0x4f, 0xb4, 0x91, 0x60, 0xa5, 0xf8, 0x8d, 0x34, 0xda, 0xc1, 0xc8, 0xc5,
	0x1a, 0x04, 0x0a, 0x14, 0x21, 0x4b, 0x2e, 0x16, 0x90, 0xbf, 0x84, 0xc4, 0xf4, 0xe0, 0xc1, 0xa2,
	0x87, 0x14, 0x26, 0x52, 0xe2, 0x18, 0xe2, 0x10, 0xa3, 0x0d, 0x18, 0x41, 0x5a, 0x41, 0xee, 0x47,
	0xd1, 0x8a, 0xe4, 0x77, 0x14, 0xad, 0xc8, 0x1e, 0x85, 0x6a, 0x2d, 0xc9, 0x47, 0xd3, 0x8a, 0xf0,
	0x23, 0xaa, 0x56, 0x24, 0x0f, 0x19, 0x30, 0x3a, 0x71, 0x47, 0x21, 0x22, 0x30, 0x89, 0x0d, 0x1c,
	0xa5, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8e, 0xbd, 0xc9, 0x8f, 0xed, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RouteClient is the client API for Route service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RouteClient interface {
	Play(ctx context.Context, in *PlayRequest, opts ...grpc.CallOption) (Route_PlayClient, error)
	Skip(ctx context.Context, in *SkipRequest, opts ...grpc.CallOption) (Route_SkipClient, error)
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (Route_StopClient, error)
}

type routeClient struct {
	cc *grpc.ClientConn
}

func NewRouteClient(cc *grpc.ClientConn) RouteClient {
	return &routeClient{cc}
}

func (c *routeClient) Play(ctx context.Context, in *PlayRequest, opts ...grpc.CallOption) (Route_PlayClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Route_serviceDesc.Streams[0], "/mojomusic.Route/Play", opts...)
	if err != nil {
		return nil, err
	}
	x := &routePlayClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Route_PlayClient interface {
	Recv() (*PlayResponse, error)
	grpc.ClientStream
}

type routePlayClient struct {
	grpc.ClientStream
}

func (x *routePlayClient) Recv() (*PlayResponse, error) {
	m := new(PlayResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *routeClient) Skip(ctx context.Context, in *SkipRequest, opts ...grpc.CallOption) (Route_SkipClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Route_serviceDesc.Streams[1], "/mojomusic.Route/Skip", opts...)
	if err != nil {
		return nil, err
	}
	x := &routeSkipClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Route_SkipClient interface {
	Recv() (*SkipResponse, error)
	grpc.ClientStream
}

type routeSkipClient struct {
	grpc.ClientStream
}

func (x *routeSkipClient) Recv() (*SkipResponse, error) {
	m := new(SkipResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *routeClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (Route_StopClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Route_serviceDesc.Streams[2], "/mojomusic.Route/Stop", opts...)
	if err != nil {
		return nil, err
	}
	x := &routeStopClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Route_StopClient interface {
	Recv() (*StopResponse, error)
	grpc.ClientStream
}

type routeStopClient struct {
	grpc.ClientStream
}

func (x *routeStopClient) Recv() (*StopResponse, error) {
	m := new(StopResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RouteServer is the server API for Route service.
type RouteServer interface {
	Play(*PlayRequest, Route_PlayServer) error
	Skip(*SkipRequest, Route_SkipServer) error
	Stop(*StopRequest, Route_StopServer) error
}

func RegisterRouteServer(s *grpc.Server, srv RouteServer) {
	s.RegisterService(&_Route_serviceDesc, srv)
}

func _Route_Play_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PlayRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RouteServer).Play(m, &routePlayServer{stream})
}

type Route_PlayServer interface {
	Send(*PlayResponse) error
	grpc.ServerStream
}

type routePlayServer struct {
	grpc.ServerStream
}

func (x *routePlayServer) Send(m *PlayResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Route_Skip_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SkipRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RouteServer).Skip(m, &routeSkipServer{stream})
}

type Route_SkipServer interface {
	Send(*SkipResponse) error
	grpc.ServerStream
}

type routeSkipServer struct {
	grpc.ServerStream
}

func (x *routeSkipServer) Send(m *SkipResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Route_Stop_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StopRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RouteServer).Stop(m, &routeStopServer{stream})
}

type Route_StopServer interface {
	Send(*StopResponse) error
	grpc.ServerStream
}

type routeStopServer struct {
	grpc.ServerStream
}

func (x *routeStopServer) Send(m *StopResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Route_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mojomusic.Route",
	HandlerType: (*RouteServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Play",
			Handler:       _Route_Play_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Skip",
			Handler:       _Route_Skip_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Stop",
			Handler:       _Route_Stop_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mojoroutes/routes.proto",
}
